# This is a basic workflow to help you get started with Actions

name: Destroy Application Infrastructure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #  paths:
  #    - 'terraform/*.tf'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  resourcegroups:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: 'Destroy container app and resources'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform init'
        id: init
        run: |
          cd terraform
          terraform init          
      - name: 'Terraform plan'
        id: plan
        run: |
          cd terraform
          terraform plan -destroy -out=terraform.plan
                    
      - name: 'Terraform apply'
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve ./terraform.plan   